name: Wails Cross-Platform Build

on:
  push:
    tags:
      - "v*" # Triggers when you push a version tag like v1.0.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "my-app-linux"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "my-app-windows"
            platform: "windows/amd64"
            os: "windows-latest"

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Wails App
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: "1.22"
          node-version: "20"
